### ISSUE TITLE
Advice using doctr with jekyll?

### ISSUE THREAD

**Issue by kyleniemeyer** [drdoctr/doctr#313]
So, I am trying to use doctr with jekyll on my GitHub Pages-based site; I have a custom jekyll plugin, so I can't just rely on the built-in jekyll support.

This is complicated by the fact that this is a user page (i.e., the repo is "orgname.github.io"), so it must be built from the `master` branch.

I haven't seen any examples that use jekyll with doctr, so I've mostly hacked together the `.travis.yml`:
```yaml
sudo: false
# Doctr requires python >=3.5
language: ruby
cache: bundler

# This gives Doctr the key we've generated
env:
  global:
    - secure: xxx

before_script:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=3.6 doctr
  - source activate test-environment

install:
  - bundle install

# This is the script to build the docs on travis, then deploy
script:
  - set -e
  - bundle exec jekyll build
  - doctr deploy --built-docs _site --branch-whitelist source --deploy-branch-name master .
```

I'm trying to have the website source on the `source` branch and then the content built in `_site` will be in the `master` branch for Github Pages. I added a `.nojekyll` file so that GitHub Pages doesn't try to build everything. Right now, the master branch has all of the source files as well.

However, I can't seem to get this to work. Any suggestions?
