### ISSUE TITLE
Unable to restrict deploy on tags only

### ISSUE THREAD

**Issue by guillaumekln** [drdoctr/doctr#329]
Hi,

Is there a known regression regarding the combination `--build-tags --branch-whitelist`?

It seems I can't get it to work, the documentation is still deployed for new commits on master. Here is the command line I have in `.travis.yml`:

```text
doctr deploy --build-tags --branch-whitelist --built-docs docs/build .
```

Thanks.

**Comment by asmeurer** [comment]
That definitely should work. It's the same as the command that is documented at https://drdoctr.github.io/recipes.html. 

I thought I had thoroughly tested this, but the logic from a2a60827 seems wrong.

**Comment by asmeurer** [comment]
Potential fix at https://github.com/drdoctr/doctr/pull/330. I need to test it, though.

**Comment by guillaumekln** [comment]
Hi,

Any update on this?

**Comment by asmeurer** [comment]
Sorry, I haven't had a chance to look at doctr stuff in a while. Can you manually install from my branch from #330 and test that it works?

**Comment by guillaumekln** [comment]
Thanks for the update!

I pinned your latest commit in my Travis configuration, but it seems it is still pushing from `master`. Is that possible?

```yml
install:
  - pip install git+git://github.com/drdoctr/doctr@1d7153975c9299fa066f896af6927d31f9907fdd
script:
  - set -e
  - sphinx-build docs docs/build
  - doctr deploy --build-tags --branch-whitelist --built-docs docs/build .
```
